#!/bin/bash

PATH=$PATH:/C/Qt/Qt5.0.1/Tools/MinGW/bin

#autoscan
#cp configure.scan configure.ac

echo aclocal
aclocal

echo autoconf
autoconf

echo autoheader
autoheader

echo libtoolize
libtoolize

echo automake
automake --add-missing -a --foreign

echo Doing configure
./configure --host=i686-pc-linux-gnu --host=i686-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"

make -s clean all
