#!/bin/bash

#PATH=$PATH:/C/Qt/Qt5.0.1/Tools/MinGW/bin
#PATH=$PATH:/C/Qt/Qt5.0.1/Tools/mingw64/bin
PATH=$PATH:/C/QtSDK/mingw/bin

#autoscan
#cp configure.scan configure.ac

echo aclocal
aclocal

echo autoconf
autoconf

echo autoheader
autoheader

echo libtoolize
libtoolize

echo automake
automake --add-missing -a --foreign

echo Doing configure
./configure

# http://lists.gnu.org/archive/html/automake/2008-09/msg00075.html