#!/bin/bash

ORGPATH=$PATH 

#PATH=$ORGPATH:/C/QtSDK/mingw/bin
PATH=$ORGPATH:/C/Qt/Qt5.0.1/Tools/MinGW/bin

echo Making 32 bit...

[ -d 32-bit ] || mkdir 32-bit && cd 32-bit
../configure
make -s  all
make -s dist
make -s doxygen
cd ..

if [ -d /C/Qt/Qt5.0.1/Tools/mingw64/bin ];
then

PATH=$ORGPATH:/C/Qt/Qt5.0.1/Tools/mingw64/bin

echo Making 64 bit...

[ -d 64-bit ] || mkdir 64-bit && cd 64-bit
../configure
make -s  all
make -s dist
cd ..

fi

