#!/bin/bash

#autoscan
#cp configure.scan configure.ac

echo aclocal
aclocal

echo autoconf
autoconf

echo autoheader
autoheader

echo libtoolize
libtoolize

echo automake
automake --add-missing -a --foreign

echo Doing configure
./configure

make -s clean all
#make -s dist

